"""
AutoOps Orchestrator — State Schema
====================================
Defines the canonical AutoOpsState TypedDict consumed by every LangGraph node.

RULES:
  • Every field name is EXACT — do NOT rename or convert to camelCase.
  • The schema is FROZEN — do NOT add, remove, or reorder fields.
  • audit_feedback uses Annotated[..., operator.add] so parallel guard
    nodes can each append their own list entries during fan-in.
"""

from typing import TypedDict, List, Dict, Any, Literal
from typing import Annotated
from operator import add


class AutoOpsState(TypedDict):
    """Shared state passed between all LangGraph nodes.

    Fields
    ------
    payload_type : Literal['onboarding','meeting_transcript','sla_check']
        Classification of the inbound payload.
    raw_payload : Dict[str, Any]
        The original, unmodified payload as received from the webhook.
    hire_profile : Dict[str, Any]
        Parsed employee / hire profile extracted from the payload.
    payload_confidence : float
        0.0–1.0 confidence score assigned by node_ingestion.
    integrity_check_passed : bool
        Whether the payload passed structural / schema integrity checks.
    historical_context : Any
        RAG retrieval result — list[dict] of similar past cases, or the
        sentinel string ``'NULL_CONTEXT'`` when nothing is found.
    similarity_gate_passed : bool
        True if the retrieved context is relevant enough to proceed.
    proposed_plan : Dict[str, Any]
        The action plan generated by node_plan_generation.
    reflection_passed : bool
        Whether the plan survived self-reflection / validation.
    security_feedback : Dict[str, Any]
        Output of the security guard agent.
    hr_feedback : Dict[str, Any]
        Output of the HR compliance guard agent.
    policy_feedback : Dict[str, Any]
        Output of the corporate-policy guard agent.
    sla_feedback : Dict[str, Any]
        Output of the SLA / performance guard agent.
    audit_feedback : Annotated[List[Dict[str, Any]], add]
        Accumulated audit trail from ALL guard nodes.  Uses the ``add``
        reducer so entries from parallel fan-out branches are concatenated
        rather than overwritten.
    meta_governance_decision : Dict[str, Any]
        Aggregated governance verdict (advance / loop / escalate).
    condenser_summary : str
        Final human-readable summary produced by node_feedback_loop.
    iteration_count : int
        Number of plan-generation loops completed so far.
    execution_log : List[Dict[str, Any]]
        Timestamped log of every execution attempt and its outcome.
    hitl_status : Literal['pending','approved','rejected','timed_out']
        Current human-in-the-loop review status.
    hitl_approvers : List[str]
        List of approver identifiers who acted on the HITL request.
    zero_shot_success : bool
        True if the plan executed successfully on the first attempt.
    execution_receipt : Dict[str, Any]
        Final receipt / confirmation artifact from node_execution.
    """

    payload_type: Literal['onboarding', 'meeting_transcript', 'sla_check']
    raw_payload: Dict[str, Any]
    hire_profile: Dict[str, Any]
    payload_confidence: float
    integrity_check_passed: bool
    historical_context: List[Dict[str, Any]] | str
    similarity_gate_passed: bool
    proposed_plan: Dict[str, Any]
    reflection_passed: bool
    pydantic_retry_count: int  # tracks Pydantic validation retries across node re-entries
                               # reset to 0 ONLY when reflection_passed becomes True
                               # do NOT reset on meta-governance loop-back
    security_feedback: Dict[str, Any]
    hr_feedback: Dict[str, Any]
    policy_feedback: Dict[str, Any]
    sla_feedback: Dict[str, Any]
    audit_feedback: Annotated[List[Dict[str, Any]], add]
    meta_governance_decision: Dict[str, Any]
    condenser_summary: str
    iteration_count: int
    execution_log: List[Dict[str, Any]]
    hitl_status: Literal['pending', 'approved', 'rejected', 'timed_out']
    hitl_approvers: List[str]
    zero_shot_success: bool
    execution_receipt: Dict[str, Any]
